<a href="https://colab.research.google.com/github/subashinianand/1m1b-project-/blob/main/DV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as snd

In [38]:
df=pd.read_csv("/content/healthcare_dataset.csv")

In [39]:
df.head()

,Patient_ID,Gender,Age,Medical_Condition,Admission_Date,Admission_Type,Medical_Code,Billing_Amount,Discharge_Date
0,P1001,Male,45,Hypertension,15-01-2026,Urgent,ICD10 I10,4500.0,20-01-2026
1,P1002,Female,32,Pneumonia,16-01-2026,Emergency,ICD10 J18,6700.5,22-01-2026
2,P1003,Male,68,Diabetes Type 2,16-01-2026,Routine,ICD10 E11,3200.0,18-01-2026
3,P1004,Female,55,Asthma,17-01-2026,Emergency,ICD10 J45,5800.0,19-01-2026
4,P1005,Male,29,Fracture,17-01-2026,Urgent,ICD10 S52,8500.0,25-01-2026

In [40]:
df.columns

Index(['Patient_ID', 'Gender', 'Age', 'Medical_Condition', 'Admission_Date',
       'Admission_Type', 'Medical_Code', 'Billing_Amount', 'Discharge_Date'],
      dtype='object')

In [41]:
df.shape

(500, 9)

In [42]:
df.isnull().sum()

Patient_ID            0
Gender                0
Age                   0
Medical_Condition     0
Admission_Date        0
Admission_Type        0
Medical_Code         15
Billing_Amount        0
Discharge_Date        0
dtype: int64

In [43]:
df['Medical_Code'].isnull().sum()

np.int64(15)

In [44]:
df['Discharge_Data']=(pd.to_datetime(df['Discharge_Date']))

/tmp/ipykernel_1703/4134515682.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Discharge_Data']=(pd.to_datetime(df['Discharge_Date']))

In [45]:
df['Admission_Type'] = df['Admission_Type'].str.lower()

In [46]:
df.describe()

              Age  Billing_Amount              Discharge_Data
count  500.000000       500.00000                         500
mean    50.106000      7249.00100  2026-05-22 17:51:21.600000
min     22.000000      2300.00000         2026-01-18 00:00:00
25%     37.000000      4400.00000         2026-03-20 18:00:00
50%     50.000000      6950.00000         2026-05-22 12:00:00
75%     63.000000      9400.00000         2026-07-24 06:00:00
max     78.000000     14200.00000         2026-09-26 00:00:00
std     15.328035      3198.96932                         NaN

In [47]:
df['Admission_Data'] = pd.to_datetime(df['Admission_Date'], dayfirst=True)
df["Hospital_Stay_Dates"]=(df["Discharge_Data"]-df['Admission_Data']).dt.days
df["Hospital_Stay_Dates"].head()

0    5
1    6
2    2
3    2
4    8
Name: Hospital_Stay_Dates, dtype: int64

In [48]:
df['Billing_Amount'].describe()

count      500.00000
mean      7249.00100
std       3198.96932
min       2300.00000
25%       4400.00000
50%       6950.00000
75%       9400.00000
max      14200.00000
Name: Billing_Amount, dtype: float64